name: diffutil_dart
description: Calculate the difference between two lists. Used for implicitly animating Flutter lists without having to maintain a StatefulWidget.
version: 0.0.2
author: Martin Kamleithner
homepage: https://github.com/knaeckeKami/diffutil.dart

environment:
  sdk: ">=2.6.0 <3.0.0"




